version: "3"

services:
  blackshell:
    build: .
    image: skaben/blackshell:latest
    volumes:
      - ./app:/opt/app
      - ./entrypoint.sh:/opt/entrypoint.sh
      - node_volume:/opt/app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=True
      - BROWSER=None
    ports:
      - 3000:3000

  mock-server:
    image: clue/json-server
    volumes:
      - ./mock/db.json:/data/db.json
    ports:
      - 5000:80

volumes:
  node_volume: {}